# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Azure subscription 1 (eea2b7a8-5ae8-4184-94d7-18ec1c91b9b3)'
    KeyVaultName: 'ComputerVisionServicesX'
    SecretsFilter: '*'
    RunAsPreJob: false
    
- script: echo $(Password) > secret.txt

- publish: secret.txt